name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      # 公式のCI, Github Actionを使用
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "lts"
          cache: true # 依存関係のキャッシュも自動で実行
          run-install: true # 自動でvp installを実行

      - name: Build with Vite+
        run: vp build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
